# Generated by Django 4.2.6 on 2023-10-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photos',
        ),
    ]
